package datos;
// Generated 22-ene-2017 18:04:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Historicoprofesores generated by hbm2java
 */
public class Historicoprofesores implements java.io.Serializable {

	private String codProf;
	private String nombre;
	private Date alta;
	private Date fechaNacimiento;

	public Historicoprofesores() {
	}

	public Historicoprofesores(String codProf) {
		this.codProf = codProf;
	}

	public Historicoprofesores(String codProf, String nombre, Date alta, Date fechaNacimiento) {
		this.codProf = codProf;
		this.nombre = nombre;
		this.alta = alta;
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getCodProf() {
		return this.codProf;
	}

	public void setCodProf(String codProf) {
		this.codProf = codProf;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getAlta() {
		return this.alta;
	}

	public void setAlta(Date alta) {
		this.alta = alta;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

}
