package datos;
// Generated 22-ene-2017 18:04:01 by Hibernate Tools 3.4.0.CR1

/**
 * Horario generated by hbm2java
 */
public class Horario implements java.io.Serializable {

	private HorarioId id;
	private Tramohorario tramohorario;
	private Asignatura asignatura;
	private Curso curso;

	public Horario() {
	}

	public Horario(HorarioId id, Tramohorario tramohorario, Asignatura asignatura, Curso curso) {
		this.id = id;
		this.tramohorario = tramohorario;
		this.asignatura = asignatura;
		this.curso = curso;
	}

	public HorarioId getId() {
		return this.id;
	}

	public void setId(HorarioId id) {
		this.id = id;
	}

	public Tramohorario getTramohorario() {
		return this.tramohorario;
	}

	public void setTramohorario(Tramohorario tramohorario) {
		this.tramohorario = tramohorario;
	}

	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

}
