package datos;
// Generated 22-ene-2017 18:04:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private String codProf;
	private String nombre;
	private String apellidos;
	private Date fechaAlta;
	private Set<Reparto> repartos = new HashSet<Reparto>(0);
	private Set<Curso> cursos = new HashSet<Curso>(0);

	public Profesor() {
	}

	public Profesor(String codProf, Date fechaAlta) {
		this.codProf = codProf;
		this.fechaAlta = fechaAlta;
	}

	public Profesor(String codProf, String nombre, String apellidos, Date fechaAlta, Set<Reparto> repartos,
			Set<Curso> cursos) {
		this.codProf = codProf;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaAlta = fechaAlta;
		this.repartos = repartos;
		this.cursos = cursos;
	}

	public String getCodProf() {
		return this.codProf;
	}

	public void setCodProf(String codProf) {
		this.codProf = codProf;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Set<Reparto> getRepartos() {
		return this.repartos;
	}

	public void setRepartos(Set<Reparto> repartos) {
		this.repartos = repartos;
	}

	public Set<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(Set<Curso> cursos) {
		this.cursos = cursos;
	}

}
